### ISSUE TITLE
Issue with integrated Code by clicking on an Event at Service Management 

### ISSUE THREAD

**Issue by obi5747** [Nepomuk1999/ConcertMaster#17]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at Domain.Event.RehearsalEventDomain.getGeneralInstrumentation(RehearsalEventDomain.java:212)
	at GUI.Duty.DutyController.initGenericTableForMusicians(DutyController.java:216)
	at GUI.Duty.DutyController.lambda$setUpListener$4(DutyController.java:140)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
![image](https://cloud.githubusercontent.com/assets/25976716/26468208/e1647cfa-4195-11e7-838a-b2c3198e8783.png)

**Comment by hrh5775** [comment]
not relevant anymore
